import { AgentExecutionContext, AgentExecutionResult, PlanStep, GeneratedArtifact } from '../../core/types';

export async function executeArchitectureAgent(step: PlanStep, context: AgentExecutionContext): Promise<AgentExecutionResult> {
  const target = context.targetEnvironment;
  const pc = target?.platformConfig as unknown as Record<string, string> | undefined;

  const schema = pc?.['schema'] || context.settings.defaultSnowflakeSchema || 'PUBLIC';
  const database = pc?.['database'] || context.settings.defaultSnowflakeDatabase || 'CURATED_DB';
  const tableName = `${step.id.replace(/[^a-zA-Z0-9_]/g, '_')}_curated`;

  const ddl = `CREATE OR REPLACE TABLE ${database}.${schema}.${tableName} (
    id STRING,
    run_id STRING,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    payload VARIANT
);

CREATE OR REPLACE VIEW ${database}.${schema}.${tableName}_view AS
SELECT * FROM ${database}.${schema}.${tableName};`;

  const modelingApproach = target?.modelingApproach || 'dimensional';
  const transformationTool = target?.transformationTool || 'dbt';
  const orchestrationTool = target?.orchestrationTool || 'airflow';

  context.log(`Architecture agent for ${step.id} produced DDL for ${modelingApproach} model via ${transformationTool}`);

  // Generate architecture documentation
  const docContent = `# Architecture Documentation: ${tableName}

## Target Environment
- **Platform:** ${target?.platform || 'snowflake'}
- **Database:** ${database}
- **Schema:** ${schema}
- **Modeling Approach:** ${modelingApproach}
- **Transformation Tool:** ${transformationTool}
- **Orchestration Tool:** ${orchestrationTool}

## Generated DDL
\`\`\`sql
${ddl}
\`\`\`

## Pipeline Flow
1. Source data lands in staging
2. ${transformationTool} transforms data using ${modelingApproach} model
3. ${orchestrationTool} orchestrates the pipeline execution
4. Data is validated and loaded into ${database}.${schema}

Generated by AutoDE Architecture Agent on ${new Date().toISOString()}
`;

  const ddlArtifact: GeneratedArtifact = {
    id: `ddl-${step.id}-${Date.now()}`,
    type: 'ddl_script',
    title: `DDL: ${tableName}`,
    description: `CREATE TABLE/VIEW statements for ${database}.${schema}.${tableName}`,
    content: ddl,
    language: 'sql',
    generatedBy: 'architectureAgent',
    generatedAt: new Date().toISOString(),
    approved: false
  };

  const docArtifact: GeneratedArtifact = {
    id: `doc-${step.id}-${Date.now()}`,
    type: 'architecture_diagram',
    title: `Architecture Doc: ${tableName}`,
    description: `Architecture documentation for ${modelingApproach} model in ${database}.${schema}`,
    content: docContent,
    language: 'markdown',
    generatedBy: 'architectureAgent',
    generatedAt: new Date().toISOString(),
    approved: false
  };

  if (context.addArtifact) {
    context.addArtifact(ddlArtifact);
    context.addArtifact(docArtifact);
  }

  return {
    success: true,
    message: `Architecture step ${step.id} generated DDL and documentation for ${database}.${schema}.${tableName}.`,
    details: {
      ddl,
      docContent,
      tableName: `${database}.${schema}.${tableName}`,
      modelingApproach,
      transformationTool,
      orchestrationTool
    },
    artifacts: [ddlArtifact, docArtifact]
  };
}